---
name: dev_container
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2
      - name: Login to Quay.io
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        env:
          QUAY_URI: quay.io/ceph-infra/teuthology-dev
          QUAY_TAG: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
        with:
          context: .
          file: containers/teuthology-dev/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.QUAY_URI }}:${{ env.QUAY_TAG }}
          outputs: type=image,name=target
